# Generated by Django 3.0.8 on 2020-08-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.Home'),
        ),
    ]
